################################################################################
# ------------------------------- USER INPUTS -------------------------------- #
################################################################################

# ----------------------- 2D Sheet ----------
[2D]
mat = {mat}# Material ID "mp-2815" MoS2 "mp-1634" MoSe2
cif_path = ../tribo_2D/cif/{mat}.cif
x = 100 # length of sheet in nm
y = 100 # width of sheet in nm
pot_path = ../tribo_2D/Potentials/sw/sw_lammps/{mat}.sw #potential path
pot_type = sw
stack_type = AB # AB or AA
lat_c =  # lattice constant in Angstrom (default is 6)

# ----------------------- General -----------
[general]
temp = 0 # in K
pressure = [-0.5, -0.1, 0.01, 0.05,0.1,0.5, 0.8, 1, 5, 10, 20, 50, 100] # in GPa
scan_angle = [2,4,90,1] # Scan Angle [lower limit, upper limit, interval, force nN or 'all'], or a single value in degrees
bond_spring = 5 # in eV/A^2 (5 is default)
scan_speed = 1 # scan speed m/s
driving_spring = 50 # spring constant in N/m