#!/bin/bash
#PBS -l select=1:ncpus=32:mem=62gb:mpiprocs=32
#PBS -l walltime=20:00:00
#PBS -J 1-156
#PBS -o /rds/general/user/mv923/home/logs_system_1/100x100_^array_index^_out.txt
#PBS -e /rds/general/user/mv923/home/logs_system_1/100x100_^array_index^_err.txt


module purge
module load tools/prod
module load LAMMPS/29Aug2024-foss-2023b-kokkos
MAT=$(sed -n "${PBS_ARRAY_INDEX}p" $PBS_O_WORKDIR/materials_list.txt)

mkdir -p $TMPDIR/afm/${MAT}/100x_100y/
rsync -av --exclude='*.lammpstrj' $HOME/afm/${MAT}/100x_100y/ $TMPDIR/afm/${MAT}/100x_100y/

#Go to the temp directory (ephemeral) and create a new folder for this run
cd $TMPDIR

# $PBS_O_WORKDIR is the directory where the pbs script was sent from.
mpirun lmp -l none -in afm/${MAT}/100x_100y/sub_aSi_tip_Si_r25/K300/l_2/lammps/system.lmp
mpirun lmp -l none -in afm/${MAT}/100x_100y/sub_aSi_tip_Si_r25/K300/l_2/lammps/slide_2ms.lmp

cp -r $TMPDIR/afm/${MAT}/100x_100y/sub_aSi_tip_Si_r25/K300/{results,visuals} $PBS_O_WORKDIR/afm/${MAT}/100x_100y/sub_aSi_tip_Si_r25/K300/
